  # --------------------------- #
  # Criador: UmGamer_
  # Discord: [Dev]UmGamer_#6392
  # Versão: 1.0
  # --------------------------- #

motd:
  ingame: "&a Bem-vindo ao servidor! Aproveite!"
  serverlist: "&b meu servidor!"